model_dir: multi_source_model

data:
  train_features_file:
    - corpus/train.bpe.uy
    - - corpus/train.source.stem
      - corpus/train.source.pos
      - corpus/train.source.suffix
      - corpus/train.source.tag
  train_labels_file: corpus/train.bpe.ch

  eval_features_file:
    - corpus/val.bpe.uy
    - - corpus/val.source.stem
      - corpus/val.source.pos
      - corpus/val.source.suffix
      - corpus/val.source.tag
  eval_labels_file: corpus/val.bpe.ch

  source_vocabulary: corpus/uy.vocab
  stem_vocabulary: corpus/morph.stem.vocab
  pos_vocabulary: corpus/pos.vocab
  suffix_vocabulary: corpus/combined.suffix.vocab
  tag_vocabulary: corpus/combined.tag.vocab
  target_vocabulary: corpus/ch.vocab

params:
  optimizer: AdamOptimizer
  optimizer_params:
    beta1: 0.9
    beta2: 0.999
  learning_rate: 0.0002
  param_init: 0.1
  clip_gradients: 5.0
  
  regularization:
    type: l2 
    scale: 1e-4

  decay_type: exponential_decay
  decay_params:
    decay_rate: 0.7
    decay_steps: 10000
  start_decay_steps: 50000
  beam_width: 5
  label_smoothing: 0.1
  length_penalty: 0.2
  dropout: 0.3

train:
  batch_size: 128
  bucket_width: 5
  save_checkpoints_steps: 5000
  keep_checkpoint_max: 5
  train_steps: 120000
  maximum_features_length: 80
  maximum_labels_length: 80
  average_last_checkpoints: 5

eval:
  batch_size: 32
  eval_delay: 1200
  external_evaluators: BLEU

infer:
  bucket_width: 5

score:
  batch_size: 32
